export default {
    DATA: {
        tileWidth: 64,
        tileHeight: 64,
        tileScale: 1.25,
        bgType: 'soil',
    },
    TYPES: {
        CONCRETE: {
            // Meant to be under buildings and around the bottom of the map etc...
            TYPE: 'stone',
            KEY: 'stone.png',
            LOOT: false,
            DRILLABLE: false,
            IGNOREBG: true, // Whether or not it uses bgType from data to append key.
        },
        DIRT: {
            TYPE: 'dirt',
            KEY: 'dirt00.png',
            LOOT: false,
            DRILLABLE: true,
            DENSITY: 600,
            IGNOREBG: true,
        },
        GRASS: {
            TYPE: 'grass',
            KEY: 'grass.png',
            LOOT: false,
            DRILLABLE: true,
            DENSITY: 600,
            IGNOREBG: true,
        },
        COAL: {
            TYPE: 'coal',
            KEY: '001_coal.png',
            WEIGHT: 1,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 900,
            VALUE: 500,
        },
        COPPER: {
            TYPE: 'copper',
            KEY: '002_copper.png',
            WEIGHT: 2,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 1200,
            VALUE: 750,
        },
        IRON: {
            TYPE: 'iron',
            KEY: '003_iron.png',
            WEIGHT: 3,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 1500,
            VALUE: 1000,
        },
        SILVER: {
            TYPE: 'silver',
            KEY: '004_silver.png',
            WEIGHT: 5,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 2000,
            VALUE: 2000,
        },
        LAPIS_LAZULI: {
            TYPE: 'lapis lazuli',
            KEY: '005_lapis_lazuli.png',
            WEIGHT: 5,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 1500,
            VALUE: 4000,
        },
        GOLD: {
            TYPE: 'gold',
            KEY: '006_gold.png',
            WEIGHT: 10,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 3000,
            VALUE: 6000,
        },
        DIAMOND: {
            TYPE: 'diamond',
            KEY: '007_diamond.png',
            WEIGHT: 10,
            LOOT: true,
            DRILLABLE: true,
            DENSITY: 4000,
            VALUE: 10000,
        },
    },
};
